framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed
        
        transports:                        
            failed: 'doctrine://default?queue_name=failed'
            # failed: 
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%/messages_failed'
            # serializer: messenger.transport.symfony_serializer
            #     options:
            #         exchange:
            #             name: messages_failed
            #         queues:
            #             messages_failed: ~
            # sync: 'sync://'

        routing:
            # Route your messages to the transports