App\Entity\Main\Module:
    attributes:
        # id:
        #     groups:
        #         - 'module'
        uuid:
            groups:
                - 'module'
                - 'systemRole'
        name:
            groups:
                - 'module'
                - 'systemRole'
        code:
            groups:
                - 'module'
                - 'systemRole'
        active: 
            groups:
                - 'module'